
- id: doi:10.1093/plphys/kiac153
  image: https://academic.oup.com/view-large/figure/363705174/kiac153f6.tif

- id: doi:10.1093/plphys/kiaf408
  image: https://academic.oup.com/view-large/figure/542534472/kiaf408f2.jpg

